In [1]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

Implement Mean Absolute Error






In [2]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [3]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

Implement same thing using numpy in much easier way

In [4]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [5]:
np.mean(np.abs(y_predicted-y_true))


0.5

In [6]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))


In [7]:
mae_np(y_predicted, y_true)

0.5

Implement Log Loss or Binary Cross Entropy

In [9]:
np.log([0])

/var/folders/3l/55sl5_m12kd2b8t3_q3w0c_h0000gn/T/ipykernel_36145/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
epsilon = 1e-15
np.log([1e-15])

array([-34.53877639])

In [11]:
y_predicted

array([1, 1, 0, 0, 1])

In [12]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [13]:
1-epsilon

0.999999999999999

In [14]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [15]:
y_predicted_new = np.array(y_predicted_new)

In [16]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [17]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [18]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
log_loss(y_true, y_predicted)


17.2696280766844

Exercise

Implement mean squared error (or MSE) in two ways,

Without using numpy (i.e. using plain python)

With the use of numpy

In [19]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse
mse(y_true, y_predicted)


Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

Solution 2: By using numpy


In [20]:
np.mean(np.square(y_true-y_predicted))

0.366